name: test build for Arch Linux

on:
  push:
    branches: master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-PKGBUILD: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and Package
        uses: heyhusen/archlinux-package-action@v3.0.0
