name: build for Arch Linux

on:
  release:
    types: published

# for testing only \/
#on:
  #push:
    #branches: master

# back to normal stuff
env:
  CARGO_TERM_COLOR: always

jobs:
  package-arch: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and Package
        uses: heyhusen/archlinux-package-action@v3.0.0
