name: Build for macOS
on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-arm64:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}

    - run: mkdir -p meowsn.app/Contents/MacOS
    - run: mkdir meowsn.app/Contents/Resources
    - run: cp assets/Info.plist meowsn.app/Contents
    - run: cp assets/meowsn.icns meowsn.app/Contents/Resources
    - run: cp target/${{ matrix.BUILD_TARGET }}/meowsn meowsn.app/Contents/MacOS
      
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: meowsn-macos-arm64
        path: meowsn.app

  macos-x86-64:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4

    - name: Install x86 target
      run: rustup target install x86_64-apple-darwin
      
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --target x86_64-apple-darwin --profile ${{ matrix.BUILD_TARGET }}

    - run: mkdir -p meowsn.app/Contents/MacOS
    - run: mkdir meowsn.app/Contents/Resources
    - run: cp assets/Info.plist meowsn.app/Contents
    - run: cp assets/meowsn.icns meowsn.app/Contents/Resources
    - run: cp target/x86_64-apple-darwin/${{ matrix.BUILD_TARGET }}/meowsn meowsn.app/Contents/MacOS
      
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: meowsn-macos-x64
        path: meowsn.app
